POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Cola branca",
  "quantity": 15,
  "price": 4
}

###

GET http://localhost:3000/api/products

###

PATCH http://localhost:3000/api/products/3
Content-Type: application/json

{
    "quantity": 15,
    "price": 5
}

###

DELETE http://localhost:3000/api/products/4

###